{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "{{CHART_NAME}}.fullname" . }}
  labels:
    {{- include "{{CHART_NAME}}.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "{{CHART_NAME}}.selectorLabels" . | nindent 6 }}
{{- end }}
